// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTysD5AmaCtr8oKgHfWq6lxlf14dASIRc',
    appId: '1:245053317389:web:1a5736233d5df66ca69044',
    messagingSenderId: '245053317389',
    projectId: 'sehety-1',
    authDomain: 'sehety-1.firebaseapp.com',
    databaseURL: 'https://sehety-1-default-rtdb.firebaseio.com',
    storageBucket: 'sehety-1.appspot.com',
    measurementId: 'G-XVFNGSNG70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKyt3YDi9NC4uI7ZW9MiyUBBJm6wehczM',
    appId: '1:245053317389:android:d9c8e86742ca0e88a69044',
    messagingSenderId: '245053317389',
    projectId: 'sehety-1',
    databaseURL: 'https://sehety-1-default-rtdb.firebaseio.com',
    storageBucket: 'sehety-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy4GJP7hDWRy-NTDy34aYhYnnmNt7g81g',
    appId: '1:245053317389:ios:6b820dd3838b57a3a69044',
    messagingSenderId: '245053317389',
    projectId: 'sehety-1',
    databaseURL: 'https://sehety-1-default-rtdb.firebaseio.com',
    storageBucket: 'sehety-1.appspot.com',
    iosBundleId: 'com.example.nabd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy4GJP7hDWRy-NTDy34aYhYnnmNt7g81g',
    appId: '1:245053317389:ios:6b820dd3838b57a3a69044',
    messagingSenderId: '245053317389',
    projectId: 'sehety-1',
    databaseURL: 'https://sehety-1-default-rtdb.firebaseio.com',
    storageBucket: 'sehety-1.appspot.com',
    iosBundleId: 'com.example.nabd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTysD5AmaCtr8oKgHfWq6lxlf14dASIRc',
    appId: '1:245053317389:web:38df7054f869bb01a69044',
    messagingSenderId: '245053317389',
    projectId: 'sehety-1',
    authDomain: 'sehety-1.firebaseapp.com',
    databaseURL: 'https://sehety-1-default-rtdb.firebaseio.com',
    storageBucket: 'sehety-1.appspot.com',
    measurementId: 'G-FVWF4HKZTX',
  );
}
